FCBH-2435 Plan translation (ONE>NIV, maybe others)
faithcomesbyhearing/dbp pull request #187
Opened 2020-09-21 20:17 UTC by mgonzalezs

# Description
- Fix order by adding the 'order_column' while the pl/an is being translated, without this the order of the items is not being inserted correctly causing conflicts on the translated view.

## Issue Link
[FCBH-2435](https://fullstacklabs.atlassian.net/browse/FCBH-2435) 

## How Do I QA This
- Open the app with the FCBH-2435 backend branch seletec.
- Navigate to the ONE 2021 plan
![image](https://user-images.githubusercontent.com/41348080/93816710-8000ab00-fc1d-11ea-8c62-0a3da595517c.png)
- Click on translate -> English -> NIV
- Verify you get the correct conent

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed locally.

2020-09-21 23:05 UTC, alburdette619 approved these changes

2020-09-21 23:06 UTC, bradflood requested changes
@mgonzalezs UsersController doesn't seem to be related to this PR.  I suspect there were just some formatting changes you wanted to add. If so, could you please remove from this PR and we can address UsersController separately

2020-09-21 23:25 UTC, mgonzalezs commented
@bradflood I can't commit with lint errors. Not sure how Casey committed and merged the previous PR, was merged before the approval. 
![image](https://user-images.githubusercontent.com/41348080/93830859-02499900-fc37-11ea-9154-6e4544a5efcf.png). 

These are the rules 
![image](https://user-images.githubusercontent.com/41348080/93831042-6c623e00-fc37-11ea-9ecf-987d9de85a1d.png)

These are the commands

![image](https://user-images.githubusercontent.com/41348080/93831082-8b60d000-fc37-11ea-9458-429fd6910b5f.png)

If we have lint errors we should run `composer cs-fix` or fix them manually. 

PD: I know we don't have CI yet implemented to prevent this.

2020-09-22 00:53 UTC, bradflood commented
@mgonzalezs  I will follow-up with Casey on the linting process, but won't hold up this PR.

2020-09-22 00:53 UTC, merged