FCBH-3126 fix api social login 500 error
faithcomesbyhearing/dbp pull request #270
Opened 2021-01-18 17:43 UTC by JramR7

# Description

* Find account with primary keys, if no account exists with those, create one.
* else, update the existing account with the provider_user_id

## Issue Link

[FCBH-3126](https://fullstacklabs.atlassian.net/browse/FCBH-3126)

## How Do I QA This
*identify a test userid and provider_id
* add a new row that has the same user_id, the same provider_id, and a bogus provider_user_id. 
* attempt to login with that userid / provider_id and the real provider_user_id. This will fail currently, and will pass when the fix is in

**Note:** To run the test suite refer to the Readme.md

2021-01-19 00:50 UTC, bradflood requested changes

2021-01-19 00:50 UTC, bradflood commented on app/Http/Controllers/User/UsersController.php
> -        // Link the social account provider
this logic still is not quite right.  The query is right... query Account with user_id, provider_id and project_id.  But firstOrCreate is not correct in the situation where the provider_user_id in the request does not match what was in the DB. If a record is found from the query, then compare provider_user_id to what was passed in. If they match, then all is good. If they differ, then update Account

2021-01-20 23:12 UTC, mgonzalezs approved these changes

2021-01-20 23:27 UTC, bradflood approved these changes

2021-01-20 23:27 UTC, merged